# Development Stage
FROM node:20-alpine AS dev

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

# COPY . .

RUN apk add openssl && npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]