# Development Stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

# RUN npm install --f --production
RUN npm i --production

COPY . .

EXPOSE 3000

# # Build the Next.js application
# RUN npm run build

# # Install PM2 globally
# RUN npm install pm2 -g

# # Start the Next.js application with PM2
# CMD ["pm2-runtime", "npm", "--", "start"]

CMD ["npm", "start"]