import { Grid, ScrollArea, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="red" grayColor="slate">
          <div className="grid h-screen grid-rows-[auto_1fr_auto]">
            <NavBar />
            <ScrollArea type="always" scrollbars="vertical" >
              <main className="overflow-hidden">{children}</main>
            </ScrollArea>
            {/* <ThemePanel /> */}
            <Footer />
          </div>
        </Theme>
      </body>
    </html>
  );
}
