import { ScrollArea, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./Footer";
import NavBar from "./NavBar";
import "./globals.css";
import QueryClientProvider from "./QueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          <StoreProvider>
            <Theme appearance="dark" accentColor="red" grayColor="slate">
              <div className="grid h-screen grid-rows-[auto_1fr_auto]">
                <div className="fixed top-0 w-full z-50"><NavBar /></div>
                <ScrollArea type="always" scrollbars="vertical" >
                  <main className="overflow-hidden my-24">{children}</main>
                </ScrollArea>
                {/* <ThemePanel /> */}
                <div className="fixed bottom-0 w-full z-50"><Footer /></div>
              </div>
            </Theme>
          </StoreProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
